### ISSUE TITLE
Looking for a better way to draw and refresh images

### ISSUE THREAD

**Issue by kylesurowiec** [kylesurowiec/spotify-coverflow#1]
I'm no expert with GUI's in Python, so I'm either looking for someone to implement a better way to draw images with tkinter or suggest an alternative.

My goals are:

- [ ]  Create an efficient way to draw and redraw images, as well as dynamic text.

- [ ]  Working Fullscreen across Windows/Mac OS/Linux Systems, with an exit key.

**Comment by jamesgasek** [comment]
hey, i found a really great way to update the panel only when the song is changed to avoid the flickering. This is my first time using python, i'm usually using java, so i'm pretty proud of myself.

change line 107 " time.sleep(4) # after 4 seconds destroy the previous image and labels so we can draw a new one" to:

current = get_current_playing[3]
while(get_current_playing[3] == current):
    time.sleep(1)

code might be a little off, I was too lazy to copy and paste it verbatim.
this stores the currently playing track as a variable, and checks every second if the track changed. works great! Thank you for the great project too!

**Comment by kylesurowiec** [comment]
@jgbuddy great suggestion. I'm currently on vacation but will implement/review your proposed change when I return. I you want to create a PR I can give you credit that way, otherwise I'll just mention your username in the code comments. Thanks!
